version: "3.8"
services:
  app:
    build: .
    container_name: cura_c
    ports:
      - "8080:8080"
    env_file:
      - ./.env # Specify the path to your .env file
    depends_on:
      mysql_server:
        condition: service_healthy
      mongo_server:
        condition: service_healthy
